// Issue 3: Localization.
export const strings = {
  sku: 'SKU',
  inStock: (n: number) => `${n} in stock`,
  outOfStock: 'Out of stock',
  quantity: 'Quantity',
  coupon: 'Coupon',
  couponPlaceholder: 'Enter coupon',
  apply: 'Apply',
  checkDelivery: 'Check delivery',
  check: 'Check',
  postcodePlaceholder: 'Postcode',
  addToCart: 'Add to cart',
  addToWishlist: 'Add to wishlist',
  removeFromWishlist: 'Remove from wishlist',
  tags: 'Tags',
  description: 'Description',
  reviews: 'Reviews',
  delivery: 'Delivery',
  deliveryAndReturns: 'Delivery and returns',
  sortBy: 'Sort by',
  sortOption: { newest: 'Newest', highest: 'Highest rated', lowest: 'Lowest rated' },
  loadingProduct: 'Loading product…',
  loadingReviews: 'Loading reviews…',
  loadingRecommendations: 'Loading recommendations…',
  noReviews: 'No reviews yet',
  reviewsError: 'Could not load reviews',
  somethingWrong: 'Something went wrong',
  retry: 'Retry',
  noProduct: 'No product found',
  youMayAlsoLike: 'You may also like',
  recentlyViewed: 'Recently viewed',
  viewProduct: 'View product',
  imageLabel: (n: number) => `View image ${n}`,
  ratingLabel: (rating: number) => `${rating} out of 5 stars`,
  deliveryAvailable: (days: number) => `Delivery available in ${days} days`,
  deliveryError: 'Could not check delivery right now',
  deliveryInfo: 'Delivery estimates are calculated based on stock availability and your postcode.',
};
